- name: Deploy Docker Application
  hosts: local
  tasks:

    - name: Stop existing container
      shell: docker stop backend || true

    - name: Remove old container
      shell: docker rm backend || true

    - name: Build Docker image
      shell: docker build -t backend-app /var/lib/jenkins/workspace/docker-lab/backend

    - name: Run new container
      shell: docker run -d -p 5000:5000 --name backend backend-app
